### ISSUE TITLE
PHP8 : Jeedom Error STarting Daemon

### ISSUE THREAD

**Issue by zgegkiller** [cddu33/enphase_secure#118]
AU démarage du daemon sur la version Alpha 4.4.2 sur Debian 12 ert RPI5 le démon ne veut pas démarrer.

0000|[2024-01-21 19:03:18] ERROR  : Veuillez vérifier la configuration
0001|[2024-01-21 19:37:38] ERROR  : Erreur sur la fonction deamon_start du plugin : Non-static method enphasesecur::CreaEquip() cannot be called statically

**Comment by cddu33** [comment]
Slt ça tombe bien il n'a jamais été testé avec cette architecture.
N'hésite pas a fait un pr

Php8 est valide avec jeedom?

**Comment by zgegkiller** [comment]
Salut heu c'est quoi un PR ? :-)
PHP se fait à partir de la version 4.4...

**Comment by cddu33** [comment]
PULL REQUEST, une modification du code.

Post tes log ça sera un bon début

**Comment by PCFiL** [comment]
Hello, 
tout d'abord merci pour le super taff et ton plugin, je l'utilise depuis un moment.

Je confirme j'ai la même erreur suite upgrade debian 11, php 8.3.4 et jeedom 4.4.3.

[2024-04-09 22:35:03][ERROR] : Erreur sur la fonction deamon_start du plugin : Non-static method enphasesecur::CreaEquip() cannot be called statically

php 8.* est moins permissif que php 7.* et visiblement la méthode pour call une function a changé.

cf: https://stackoverflow.com/questions/18339716/why-im-getting-non-static-method-should-not-be-called-statically-when-invokin

Je pense que ca concerne cette fonction : 
core/class/enphasesecur.class.php:      public function CreaEquip($enphaselogic, $enphasename, $enphaseconf, $enphaseconfbis, $enphasevisible, $enphaseenable) 

merci pour ce que tu pourras faire :-)

**Comment by cddu33** [comment]
Slt tes log sont où ?
Et php 8 n'est pas supporté officiellement par jeedom...

**Comment by PCFiL** [comment]
j'ai remplacé la déclaration de la fonction CreaEquip() dans le fichier core/class/enphasesecur.class.php :

public function CreaEquip => public static function CreaEquip

j'ai mis les logs en DEBUG pour valider que je n'ai plus d'err => all good !

php8 est supporté depuis la 4.4.1, cf CHANGELOG: https://doc.jeedom.com/fr_FR/core/4.4/changelog?theme=dark

merci pour ta réactivité :-)

**Comment by PCFiL** [comment]
PR crée.

**Comment by cddu33** [comment]
PR intégré à la beta
