### ISSUE TITLE
Import/Export journaliers

### ISSUE THREAD

**Issue by ugorenner** [cddu33/enphase_secure#126]
Bonjour,

Merci pour le super boulot sur ce plugin =)

J'étais intéressé par les valeurs d'import/export journalières, mais elles semblent fausses, dans le plugin mais aussi au niveau de l'export JSON de la gateway (sur lequel le plugin repose je suppose ?).

Serait-ce envisageable d'utiliser l'[API V4](https://developer-v4.enphase.com/docs.html) pour les valeurs journalières ?
Cette API donne les valeurs par créneaux de 15 minutes, comme l'application.

Elle nécessite un compte développeur et donc un plan, mais ça pourrait être à l'utilisateur de créer son application et donc de gérer son plan lui même.
Il faudrait donc rajouter des champs de configuration pour la clé, le client id, et le client secret.

Est-ce que l'architecture du plugin permettrait ça ?

Merci d'avance

**Comment by cddu33** [comment]
Slt non désolé, je ne ferais pas ce type de modif pour plusieurs raisons:
- le problème de "données fausses" arrivent chez très peu de personnes 
- le but de se plugin est d'avoir des données en temps réel ce qui ne pas le cas de l'API
- je ne suis plus sur jeedom donc je n'ai pas beaucoup de temps a y consacrer 

Mais libre a toi de faire un fork ou de récupérer totalement le plugin si tu en as les compétences
